Feat comp movies
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-Watch_now pull request #10
Opened 2023-11-16 13:48 UTC by ThibaudDps

Inclusion titre + genre + date sous poster dans la liste

CSS + responsive

2023-11-16 13:50 UTC, iNaeRoZ approved these changes
c'est good

2023-11-16 14:20 UTC, Zonzon58 approved these changes
ok

2023-11-16 14:22 UTC, Zonzon58 approved these changes
ok

2023-11-17 07:44 UTC, jujuck requested changes

2023-11-17 07:44 UTC, jujuck commented on frontend/src/style/ListMovies.css
> +h4 {
Est ce le bon endroit pour un h4 (portée globale)

2023-11-17 07:44 UTC, jujuck commented on frontend/src/style/ListMovies.css
> +  h1 {
Est ce le bon endroit pour un h1 (portée globale) ?

2023-11-17 07:44 UTC, jujuck commented on frontend/src/style/ListMovies.css
> +  h5 {
Est ce le bon endroit pour un h5 (portée globale) ?

2023-11-17 07:44 UTC, jujuck commented on frontend/src/style/ListMovies.css
> +  h5 {
Est ce le bon endroit pour un h5 (portée globale) ?

2023-11-17 07:44 UTC, jujuck commented on frontend/src/style/ListMovies.css
> +  h5 {
Est ce le bon endroit pour un h5 (portée globale) ?

2023-11-17 08:21 UTC, Zonzon58 approved these changes
ok

2023-11-17 09:37 UTC, merged

2023-11-17 09:37 UTC, jujuck approved these changes