Feat displayby
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-Watch_now pull request #2
Opened 2023-10-27 10:10 UTC by Zonzon58

2023-10-27 10:11 UTC, iNaeRoZ submitted a review, later dismissed
Le code est bon pour ma part

2023-10-27 10:16 UTC, ThibaudDps approved these changes

2023-11-10 10:37 UTC, ThibaudDps approved these changes

2023-11-10 10:38 UTC, Zonzon58 commented
ok

2023-11-10 10:40 UTC, Zonzon58 commented
ok

2023-11-14 15:10 UTC, jujuck requested changes

2023-11-15 09:43 UTC, merged