Feat navbar
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-Watch_now pull request #5
Opened 2023-11-09 15:24 UTC by ThibaudDps

Ajout Navbar + navigation modal en responsive

css + react done

2023-11-10 08:35 UTC, iNaeRoZ approved these changes
Le code est bon !

2023-11-10 08:43 UTC, Zonzon58 approved these changes
bien vu

2023-11-14 13:43 UTC, jujuck requested changes

2023-11-14 13:43 UTC, jujuck commented on frontend/src/components/ListMovies.jsx
> +    <div id="list-movies">
Pas d'id

2023-11-14 13:43 UTC, jujuck commented on frontend/src/components/ListMovies.jsx
> +          <div>
Faire un composant

2023-11-14 13:43 UTC, jujuck commented on frontend/src/components/NavBar.jsx
> +      <nav id="nav-menu">
Pas d'id non plus

2023-11-14 13:43 UTC, jujuck commented on frontend/src/components/NavbarModal.jsx
> +      <nav id="nav-menu-modal">
idem pas d'id

2023-11-14 13:43 UTC, jujuck commented on frontend/src/main.jsx
> +        .get("http://localhost:3310/api/movies")
Passer en variable d'environnement les url ${import.meta.env.VITE_BACKEND_URL} au lien de http://localhost:3310

2023-11-14 13:43 UTC, jujuck commented on frontend/src/main.jsx
> +        .get("http://localhost:3310/api/movies")
Passer en variable d'environnement les url ${import.meta.env.VITE_BACKEND_URL} au lien de http://localhost:3310

2023-11-14 13:43 UTC, jujuck commented on frontend/src/pages/MoviePage.jsx
> +      <div>
Réutiliser le composant crée précedement dans movieList

2023-11-14 13:43 UTC, jujuck commented on frontend/src/style/ListMovies.css
> +h1 {
Le passer en css global dans le index.css (import dans le main.jsx)

2023-11-14 13:43 UTC, jujuck commented on frontend/src/style/ListMovies.css
> +h2 {
Le passer en css global dans le index.css (import dans le main.jsx)

2023-11-14 13:43 UTC, jujuck commented on frontend/src/style/ListMovies.css
> +  #list-movies {
Pas d'id pour le css

2023-11-14 13:43 UTC, jujuck commented on frontend/src/style/ListMovies.css
> +  h1 {
Le passer en css global dans le index.css (import dans le main.jsx)

2023-11-14 13:43 UTC, jujuck commented on frontend/src/style/ListMovies.css
> +  #list-movies {
Pas d'id dans le css

2023-11-14 13:43 UTC, jujuck commented on frontend/src/style/ListMovies.css
> +  #list-movies {
Pas d'id dans le css

2023-11-14 13:43 UTC, jujuck commented on frontend/src/style/ListMovies.css
> +  #list-movies {
Pas d'id dans le css

2023-11-14 13:43 UTC, jujuck commented on frontend/src/style/ListMovies.css
> +  h1 {
Le passer en css global dans le index.css (import dans le main.jsx)

2023-11-14 13:43 UTC, jujuck commented on frontend/src/style/ListMovies.css
> +  h2 {
Le passer en css global dans le index.css (import dans le main.jsx)

2023-11-14 13:43 UTC, jujuck commented on frontend/src/style/ListMovies.css
> +  #list-movies {
Pas d'id

2023-11-14 13:43 UTC, jujuck commented on frontend/src/style/ListMovies.css
> +  #list-movies {
Pas d'id

2023-11-14 13:43 UTC, jujuck commented on frontend/src/style/ListMovies.css
> +  #list-movies {
Pas d'id

2023-11-14 13:44 UTC, closed without merging